print('Write a python program to take 3 numbers from the user and display product of those numbers.')
a = float(input('Enter first number: '))
b = float(input('Enter second number: '))
c = float(input('Enter third number: '))
print(a, '*', b, '*', c, '=', a*b*c)
